# Generated by Django 3.1.4 on 2021-01-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetail',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testdetail',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
