# Generated by Django 3.1.4 on 2021-01-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
