# Generated by Django 3.1.4 on 2021-01-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210104_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
