# Generated by Django 3.1.4 on 2021-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
