# Generated by Django 3.1.4 on 2021-01-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
