# Generated by Django 3.1.4 on 2021-01-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210105_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='TestDetail',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testdetail')),
            ],
        ),
    ]
