# Generated by Django 3.1.4 on 2021-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210105_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
