# Generated by Django 3.1.4 on 2021-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
